Update packages
Specify openssl specifically for monkeysphere

which is failing with this error:

ERROR: unsatisfiable constraints:
  cmd:openssl (virtual):
    provided by: openssl openssl3.0
    required by: monkeysphere-0.44-r0[cmd:openssl]